### ISSUE TITLE
Crashing & errors

### ISSUE THREAD

**Issue by hwine** [mozilla-services/GitHub-Audit#43]
Not gracefully handling errors for at least 2 cases:
- bad sleep calc (near top of [output](#logs))
- tinydb being passed invalid data after 502 (near bottom of [output](#logs))

### Logs:
There are several similar failures -- see log in Jenkins. E.g. from [prod jenkins](https://ops-master.jenkinsv2.prod.mozaws.net/job/security/job/metrics/job/foxsec-metrics-github-repo/217/display/redirect): 

```
Backing off ag_call_with_rc(...) for 0.3s (AG_Exception)
2019-06-27 03:35:19,042 INFO: Backing off ag_call_with_rc(...) for 0.3s (AG_Exception)
2019-06-27 03:41:40,179 ERROR: pass time calc: remaining: 19, karma: 25
2019-06-27 03:41:40,179 ERROR:                reset: 1561607856, now: 1561606900.1791952, nap: 955.8208048343658
2019-06-27 03:41:40,179 INFO: napping for 955.8208048343658 seconds
2019-06-27 03:57:36,160 ERROR: FAIL time calc: remaining: 19, karma: 25
2019-06-27 03:57:36,160 ERROR:                reset: 1561611456, now: 1561607856.1602778, nap: 3599.8397221565247
2019-06-27 03:57:36,160 INFO: napping for 3599.8397221565247 seconds
2019-06-27 05:21:39,814 ERROR: 502 for /repos/mozilla/webmaker-analytics/hooks
Backing off ag_call_with_rc(...) for 0.7s (AG_Exception)
2019-06-27 05:21:39,814 INFO: Backing off ag_call_with_rc(...) for 0.7s (AG_Exception)
2019-06-27 06:24:01,668 ERROR: 502 for /repos/mozilla/node-firefox-examples-install-packaged
Backing off ag_call_with_rc(...) for 0.5s (AG_Exception)
2019-06-27 06:24:01,668 INFO: Backing off ag_call_with_rc(...) for 0.5s (AG_Exception)
2019-06-27 10:33:03,976 ERROR: 502 for /repos/mozilla/moz-console/branches/master
Backing off ag_call_with_rc(...) for 0.3s (AG_Exception)
2019-06-27 10:33:03,976 INFO: Backing off ag_call_with_rc(...) for 0.3s (AG_Exception)
2019-06-27 10:48:24,616 ERROR: 504 for /repos/mozilla/protocol/hooks
Backing off ag_call_with_rc(...) for 1.0s (AG_Exception)
2019-06-27 10:48:24,616 INFO: Backing off ag_call_with_rc(...) for 1.0s (AG_Exception)
2019-06-27 11:34:00,328 ERROR: 502 for /repos/mozilla/nmap-agent/branches
Backing off ag_call_with_rc(...) for 0.6s (AG_Exception)
2019-06-27 11:34:00,328 INFO: Backing off ag_call_with_rc(...) for 0.6s (AG_Exception)
2019-06-27 12:44:47,534 ERROR: 502 for /repos/mozilla/popup-urls/branches/master
Backing off ag_call_with_rc(...) for 0.4s (AG_Exception)
2019-06-27 12:44:47,534 INFO: Backing off ag_call_with_rc(...) for 0.4s (AG_Exception)
Traceback (most recent call last):
  File "./get_branch_protections.py", line 580, in <module>
    main()
  File "./get_branch_protections.py", line 545, in main
    data = process_orgs(args, collected_as=collected_as)
  File "./get_branch_protections.py", line 522, in process_orgs
    org_data = harvest_org(org)
  File "./get_branch_protections.py", line 464, in harvest_org
    repo_data = harvest_repo(repo)
  File "./get_branch_protections.py", line 378, in harvest_repo
    branch = ag_call(gh.repos[full_name].branches[default_branch].get)
  File "./get_branch_protections.py", line 90, in ag_call
    _, body = ag_call_with_rc(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "./get_branch_protections.py", line 158, in ag_call_with_rc
    last_table.upsert(doc, tinydb.where("url") == url)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/database.py", line 571, in upsert
    return [self.insert(document)]
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/database.py", line 450, in insert
    self._write(data)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/database.py", line 410, in _write
    self._storage.write(values)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/database.py", line 116, in write
    self._storage.write(raw_data)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/storages.py", line 112, in write
    serialized = json.dumps(data, **self.kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
moz_scripts/Makefile:37: recipe for target 'mozilla.db.json' failed
make: *** [mozilla.db.json] Error 1
```

**Comment by hwine** [comment]
sleep issue addressed elsewhere. Serializable is now covered in #51
