### ISSUE TITLE
Intermittant Serialization Failures

### ISSUE THREAD

**Issue by hwine** [mozilla-services/GitHub-Audit#51]
A log of when it occurs:
- 2019-10-11 in Jenkins. Could not repro on laptop, next day's run successfully ([details](https://github.com/mozilla-services/GitHub-Audit/issues/51#issuecomment-541326757))

**Comment by hwine** [comment]
2019-10-11 details:
```
./get_branch_protections.py mozilla.db.json
2019-10-11 02:57:36,217 INFO: Running as moz-hwine
2019-10-11 02:57:36,334 INFO: Gathering branch protection data. (calls remaining 4999).
2019-10-11 02:57:36,446 INFO: Starting on org mozilla. (calls remaining 4999).
2019-10-11 03:40:57,505 ERROR: pass time calc: remaining: 24, karma: 25
2019-10-11 03:40:57,505 ERROR:                reset: 1570766256, now: 1570765257.504984, nap: 998.4950160980225
2019-10-11 03:40:57,505 INFO: napping for 998.4950160980225 seconds
Traceback (most recent call last):
  File "./get_branch_protections.py", line 580, in <module>
    main()
  File "./get_branch_protections.py", line 545, in main
    data = process_orgs(args, collected_as=collected_as)
  File "./get_branch_protections.py", line 522, in process_orgs
    org_data = harvest_org(org)
  File "./get_branch_protections.py", line 464, in harvest_org
    repo_data = harvest_repo(repo)
  File "./get_branch_protections.py", line 401, in harvest_repo
    expected_rc=[200, 304, 404],
  File "./get_branch_protections.py", line 90, in ag_call
    _, body = ag_call_with_rc(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "./get_branch_protections.py", line 158, in ag_call_with_rc
    last_table.upsert(doc, tinydb.where("url") == url)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/database.py", line 571, in upsert
    return [self.insert(document)]
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/database.py", line 450, in insert
    self._write(data)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/database.py", line 410, in _write
    self._storage.write(values)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/database.py", line 116, in write
    self._storage.write(raw_data)
  File "/root/.cache/pypoetry/virtualenvs/github-audit-py3.6/lib/python3.6/site-packages/tinydb/storages.py", line 112, in write
    serialized = json.dumps(data, **self.kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
moz_scripts/Makefile:37: recipe for target 'mozilla.db.json' failed
make: *** [mozilla.db.json] Error 1
Build step 'Execute shell' marked build as failure
```
